# NUMPY

 np.array(lista) : Crea un array a partir de la lista o tupla lista y devuelve una referencia a él. 
        
Los elementos de la lista o tupla deben ser del mismo tipo.

In [1]:
import numpy as np

l1 = [1,2,3,4,5]
l2 = [[1,2,3],[4,5,6]]
l3 = [   [ [1,2,3],[4,5,6] ] , [ [7,8,9],[10,11,12] ]   ]
          
a1 = np.array(l1)
a2 = np.array(l2)
a3 = np.array(l3)

print(l1, type(l1))
print(l2 , type(l2))
print(a1, type(a1))
print(a2, type(a2))
print(a3, type(a3))

[1, 2, 3, 4, 5] <class 'list'>
[[1, 2, 3], [4, 5, 6]] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'>


### Otras funciones útiles que permiten generar arrays son:

np.empty(dimensiones) : Crea y devuelve una referencia a un array vacío con las dimensiones especificadas en la tupla dimensiones.

np.zeros(dimensiones) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos ceros.

np.ones(dimensiones) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos unos.

np.full(dimensiones, valor) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos valor.

np.identity(n) : Crea y devuelve una referencia a la matriz identidad de dimensión n.

np.arange(inicio, fin, salto) : Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia desde inicio hasta fin tomando valores cada salto.

np.linspace(inicio, fin, n) : Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia de n valores equidistantes desde inicio hasta fin.

np.random.random(dimensiones) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son aleatorios.

In [2]:
x1 = np.full([2,4],  77)
x2 = np.zeros([4,4], dtype=int )
xmes = np.arange(1,31,1)
xdis = np.linspace(100,10000,6)
xdado = np.random.random([2,6])


print(x1)
print(x2)
print(xmes)
print(xdis)
print(xdado)

[[77 77 77 77]
 [77 77 77 77]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[  100.  2080.  4060.  6040.  8020. 10000.]
[[0.72768467 0.89901707 0.36066757 0.4228123  0.72243767 0.87845169]
 [0.11596625 0.88497256 0.76745809 0.80362926 0.52073355 0.49428823]]


In [3]:
z = np.identity(6)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [4]:
# matriz random de 8 x 8 con valores de 60 a 65 incluyendo ambos extremos
rng = np.random.default_rng()
xruleta =  rng.integers(low=60, high=65, size=(8, 8) , endpoint=True) #endpoint dice si se incluye el high.
print(xruleta)

[[64 61 65 64 60 61 65 65]
 [62 60 60 64 60 65 65 64]
 [65 65 63 65 63 62 62 61]
 [60 63 61 65 64 64 64 65]
 [60 62 64 64 62 61 65 60]
 [61 65 65 61 61 60 62 63]
 [60 65 62 63 61 62 63 60]
 [60 64 62 62 62 65 64 63]]


**a.ndim :** Devuelve el número de dimensiones del array a.

**a.shape :** Devuelve una tupla con las dimensiones del array a.

**a.size :** Devuelve el número de elementos del array a.

**a.dtype:** Devuelve el tipo de datos de los elementos del array a.

In [5]:
print(xruleta.ndim)
print(xruleta.shape)
print(xruleta.size)
print(xruleta.dtype)

2
(8, 8)
64
int64


## Acceso a elementos de un Array

In [6]:
a1 = np.array( [ [1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500] ] )
print(a1)
print(a1[0,0])
fila = 2
columna=3
print(a1[ fila , columna ]) #empiezan en cero!!!
print(a1[ fila] [columna ]) #otra forma que sirve igual

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
1
400
400


### Filtrado de un Array

In [9]:
a1 = np.array( [ [1,2,3,4,5],[11,22,33,44,55],[111,222,333,444,555] ] )
a2 = a1[ ( a1 % 2== 0 ) ]
print(a2)

[  2   4  22  44 222 444]


### Operaciones Matematicas de un Array

In [8]:
a1 = np.array ( [ [10,20,30,40],[50,60,70,80] ])
a2 = np.array ( [ [1,1,1,1],[2,2,2,2] ])
a3 = np.array ( [ [10,10,10,10],[10,10,10,10] ])

print(a1+a2)
print(a1-a3)
print(a1*a2)


[[11 21 31 41]
 [52 62 72 82]]
[[ 0 10 20 30]
 [40 50 60 70]]
[[ 10  20  30  40]
 [100 120 140 160]]


## Aplicar una funcion a un array

In [2]:
def calculocosto(x):
    return (x-5)/2

precio = [100,200,300,250,80,350]
costo = list(map(calculocosto,precio))

print(precio)
print(costo)

[100, 200, 300, 250, 80, 350]
[47.5, 97.5, 147.5, 122.5, 37.5, 172.5]
